# Generated by Django 5.2.14 on 2026-05-09 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=100)),
                (
                    "api_name",
                    models.SlugField(
                        blank=True,
                        help_text="Stable internal name. Leave blank to generate one from the label.",
                        max_length=100,
                        unique=True,
                        verbose_name="API name",
                    ),
                ),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("number", "Number"),
                            ("date", "Date"),
                            ("email", "Email"),
                            ("phone", "Phone"),
                        ],
                        default="text",
                        max_length=20,
                    ),
                ),
                ("help_text", models.CharField(blank=True, max_length=255)),
                ("required", models.BooleanField(default=False)),
                ("active", models.BooleanField(default=True)),
                ("display_order", models.PositiveIntegerField(default=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["display_order", "label"],
            },
        ),
        migrations.CreateModel(
            name="AccountFieldValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.TextField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_values",
                        to="crm.account",
                    ),
                ),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="values",
                        to="crm.accountfield",
                    ),
                ),
            ],
            options={
                "ordering": ["field__display_order", "field__label"],
                "unique_together": {("account", "field")},
            },
        ),
    ]
