# Generated by Django 5.2.14 on 2026-05-09 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0003_accountfield_accountfieldvalue"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="account",
            name="first_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="account",
            name="tax_id_code",
            field=models.CharField(
                blank=True,
                choices=[("SSN", "SSN"), ("EIN", "EIN")],
                max_length=32,
                verbose_name="Tax ID code",
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="tax_id_number",
            field=models.CharField(
                blank=True, max_length=64, verbose_name="Tax ID number"
            ),
        ),
    ]
