# Generated by Django 5.2.14 on 2026-05-09 13:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_default_profile_object_permissions(apps, schema_editor):
    group_model = apps.get_model("auth", "Group")
    content_type_model = apps.get_model("contenttypes", "ContentType")
    profile_permission_model = apps.get_model("crm", "ProfileObjectPermission")

    admin_group, _ = group_model.objects.get_or_create(name="CRM Admin")
    standard_group, _ = group_model.objects.get_or_create(name="Standard User")

    crm_models = [
        "account",
        "accountfield",
        "accountfieldvalue",
        "product",
        "opportunity",
        "opportunitylineitem",
        "profileobjectpermission",
    ]
    for model_name in crm_models:
        content_type, _ = content_type_model.objects.get_or_create(app_label="crm", model=model_name)
        profile_permission_model.objects.update_or_create(
            profile=admin_group,
            content_type=content_type,
            defaults={
                "can_read": True,
                "can_write": True,
                "can_read_all": True,
                "can_edit_all": True,
            },
        )

    account_content_type, _ = content_type_model.objects.get_or_create(app_label="crm", model="account")
    profile_permission_model.objects.update_or_create(
        profile=standard_group,
        content_type=account_content_type,
        defaults={
            "can_read": True,
            "can_write": True,
            "can_read_all": False,
            "can_edit_all": False,
        },
    )


def remove_default_profile_object_permissions(apps, schema_editor):
    profile_permission_model = apps.get_model("crm", "ProfileObjectPermission")
    profile_permission_model.objects.filter(profile__name__in=["CRM Admin", "Standard User"]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("crm", "0005_product_opportunity_opportunitylineitem"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owned_accounts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owned_opportunities",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="ProfileObjectPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("can_read", models.BooleanField(default=False, verbose_name="Read")),
                ("can_write", models.BooleanField(default=False, verbose_name="Write")),
                (
                    "can_read_all",
                    models.BooleanField(default=False, verbose_name="Read all"),
                ),
                (
                    "can_edit_all",
                    models.BooleanField(default=False, verbose_name="Edit all"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="crm_profile_permissions",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="object_permissions",
                        to="auth.group",
                    ),
                ),
            ],
            options={
                "verbose_name": "profile object access",
                "verbose_name_plural": "profile object access",
                "ordering": [
                    "profile__name",
                    "content_type__app_label",
                    "content_type__model",
                ],
                "unique_together": {("profile", "content_type")},
            },
        ),
        migrations.RunPython(create_default_profile_object_permissions, remove_default_profile_object_permissions),
    ]
