# Generated by Django 5.2.14 on 2026-05-09 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0007_update_standard_user_object_access_defaults"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="opportunity",
            options={
                "ordering": ["-updated_at", "name"],
                "verbose_name_plural": "opportunities",
            },
        ),
    ]
